### ISSUE TITLE
Remove python folder in favor to python repo

### ISSUE THREAD

**Issue by ecarreras** [Axiacore/numero-a-letras#12]
I've found the python repo https://github.com/AxiaCore/number-to-letters and is a little messy to know which repo work on. I think it's better to work with the only python repo because is a setup.py and structured as a lib.

**Comment by camilonova** [comment]
It is, I'm going to create separate repos for each language.

**Comment by camilonova** [comment]
This should be the one https://github.com/Axiacore/number-to-letters
