### ISSUE TITLE
No toma la parte decimal 6.095,80

### ISSUE THREAD

**Issue by johnsh** [AxiaCore/numero-a-letras#5]
Hola como estan,

Al intentar convertir 6.095,80 arroja  "Seis Mil Noventa Y Cinco", como debo hacer para que tome la parte decimal, si esposible ?

Gracias.

**Comment by camilonova** [comment]
Debería ser sencillo, puedes identificar la parte decimal y convertirla a letras también.

Puedes enviarnos un PR cuando lo tengas listo.
