### ISSUE TITLE
Error al mostrar las decimas 

### ISSUE THREAD

**Issue by eduarve** [AxiaCore/numero-a-letras#6]
Saludos, tengo un problema que le he estado dando vueltas desde hace dias y no lo he podido solucionar, mira cuando tengo un numero como por ejemplo: 
360.60 -> Tres cientos sesenta con sesenta centimos 
el programa me lo saca como "Tres cientos sesenta con seis centimos" 
eso mismo pasa con todas las cantidades que terminan en 10, 20, 30, 40 etc. pero cuando es 11, 43 los muestra bien, es decir, en casos cuando es 360.65 me lo muestra "tres cientos sesenta con sesenta y cinco centimos"

**Comment by camilonova** [comment]
@eduarve prueba de nuevo con los últimos cambios, si tienes problemas volvemos a abrir el ticket.
