### ISSUE TITLE
Extensión del código

### ISSUE THREAD

**Issue by jdcaballerov** [AxiaCore/numero-a-letras#7]
Encontré ayer el código y me pareció interesante extenderlo y armar un paquete. He subido una versión sin la restricción para números mayores a mil millones en [este repositorio](https://github.com/jdcaballerov/humanizar)

Con la modificación es posible usarlo hasta los undecillones (me aburrí incluyendo más)

saludos,

**Comment by camilonova** [comment]
y porque no haces un PR y lo integramos a este?

**Comment by jdcaballerov** [comment]
vale, enviado el PR. Corregí unos tests que no pasaban por espacios y cambié el de la restricción por el valor.

**Comment by camilonova** [comment]
Listo, gracias.
